### ISSUE TITLE
Supporting a Publishing use-case

### ISSUE THREAD

**Issue by cinnamon-bun** [earthstar-project/earthstar#116]
What if you want to publish some webpages via Earthstar?  Here's a couple ways:

1. Get Earthstar support in Agregore browser by finishing [earthstar-fetch](https://github.com/earthstar-project/earthstar-fetch/).  It specifies an URL scheme for viewing workspace document data in a browser.

2. (Easier) Add a new URL pattern to [earthstar-pub](https://github.com/earthstar-project/earthstar-pub/) which, in addition to syncing, can also just serve document content as regular HTTP responses.  We could try to match the URL scheme from Earthstar-Fetch.

Number 2 is really nice -- you just spin up a pub, sync your data to it, and it acts as a web gateway for viewing webpages stored in your Earthstar documents.  You could even embed some javascript in there and distribute whole Earthstar apps that way.

We also need #7 [Invite-only workspaces](https://github.com/earthstar-project/earthstar/issues/7) so that people can read and help host the data without getting the ability to write to it.

See also in earthstar-pub, [Serve web content out of Earthstar documents right from the pub](https://github.com/earthstar-project/earthstar-pub/issues/13)

**Comment by sgwilym** [comment]
The new replica server framework has an extension for this!
