### ISSUE TITLE
Throws error when imported from  js files

### ISSUE THREAD

**Issue by khubo** [earthstar-project/earthstar#118]
While trying to import EarthStar from a javascript file it throws the below error - I am trying to create a react app
<img width="894" alt="Screenshot 2021-04-14 at 11 06 28 AM" src="https://user-images.githubusercontent.com/13710311/114659594-88cbe200-9d11-11eb-9888-0a1054931a26.png">
It is fine when the app is built using typescript though.  I suspect its a collision with the global `TextDecoder` available in the browser.

## Possible Solution
 Updating `multibase` to `v4` seems to fix the problem since it replaced the  Decoder/encoder provided by `web-encoding` lib with the global one.

**Comment by cinnamon-bun** [comment]
Thanks for catching this!  How are you building / packaging your app?

The newer `multibase` changed its API from node Buffers to browser-style Uint8Array.  The rest of Earthstar uses Buffers and depends on your app's bundler to convert that to browser code.

PR welcome!  Maybe upgrading will Just Work, maybe we'll have to mess around with converting Uint8Array back to Buffers.

To run node tests, do `npm run test`

There are 2 ways to run headless browser tests: `npm run test-in-browser-with-karma` or `npm run test-in-browser-run`.  These only run one of the test files which is set by the `browserify-for-karma` line in `package.json`.  The default test file is probably comprehensive enough, you don't need to run them all one by one.

I guess you'd also have to invent a way to test importing it from javascript :)

**Comment by cinnamon-bun** [comment]
Fixed by `earthstar@6.6.2` which replaced `multibase` with `rfc4648`
