### ISSUE TITLE
Set up RPC

### ISSUE THREAD

**Issue by cinnamon-bun** [earthstar-project/earthstar#14]
Right now sync happens over an HTTP REST API.

Generalize this using some RPC framework so it can happen over other transports too.

JSON-RPC is a good choice.

**Comment by sgwilym** [comment]
I'd like to throw in that earthstar-graphql is capable of doing this job, as it can be carried out over any transport.

**Comment by cinnamon-bun** [comment]
Hmm!  Do you think it would work over a duplex stream like you get from hyperswarm?

**Comment by sgwilym** [comment]
Yes, so you can communicate bi-directionally with a GraphQL server using 'subscriptions' (here's an implementation which can be used with graphql-js, the package earthstar-graphql uses to define its schema: https://github.com/apollographql/graphql-subscriptions)

A lot of it is very new to me, but I think (?) this is right in principle.

**Comment by cinnamon-bun** [comment]
I wrote [mini-rpc](https://github.com/earthstar-project/mini-rpc) for this purpose, now we need to hook it up in the sync and pub code.
