### ISSUE TITLE
Announce when localStorage is updated

### ISSUE THREAD

**Issue by basham** [earthstar-project/earthstar#173]
## What's the problem you want solved?

StorageLocalStorage should inform when the document is written to localStorage. I'm using the latest v6.8.0 of Earthstar. When using `storage.set()`, it synchronously returns a response regarding if the document was accepted or not. It also synchronously emits an event to the `storage.onWrite` emitter. While the changed is immediately available in memory (via `storage.getContent()`), it is not immediately written to localStorage. [Writes to localStorage are debounced](https://github.com/earthstar-project/earthstar/blob/v6.8.5/src/storage/storageLocalStorage.ts#L67-L78). This is a reasonable solution, but I should have a way to know when localStorage is updated.

In my current case, I'm submitting a form and wanting to redirect the page. I write the document, it accepts, but then I must delay redirecting the page in order to accommodate the debounce. I delay for 100ms, but because it is debouncing, I have no guarantee that it will save to localStorage in that window. If the document is not saved to localStorage before the redirect, it is lost when the memory flushes.

## Is there a solution you'd like to recommend?

There are a few things that could be done to solve this:

1. Have `storage.set()` return a Promise that resolves when the document is set in localStorage. Or maybe it returns an object with a property that includes the Promise.
2. Add a new subscription option (`storage.onSaved()`?) for whenever localStorage gets updated. As a bonus, it could provide an array of all documents part of the update, since it is internally subscribed to `onWrite()`.
3. Provide an option to force localStorage to immediately update (`storage.save()`?), in a synchronous way. If that happens, it could cancel any debouncing operation currently scheduled.

**Comment by basham** [comment]
Note: There is a [native storage event](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event), but it emits only on localStorage changes to other pages, not the source page. So, unfortunately, that is not an option.

**Comment by sgwilym** [comment]
Thank you for this detailed and considered issue!

In the long-term, this will be addressed by the next major version of Earthstar, in which all storages are asynchronous. This is the same as the first option you proposed. But that doesn't help you much now.

In the short-term, it's a little scrappy, but maybe adding a new member to [`WriteEvent`](https://github.com/earthstar-project/earthstar/blob/main/src/storage/storageTypes.ts#L18) could work? Something with type `DOCUMENT_PERSIST`?

It would help to know how you might use this feature in the app your building, e.g. is it for a UI indicator, preventing the user from closing the window, etc.

**Comment by basham** [comment]
Yes, extending WriteEvent and sending a new event at the end of `saveToLocalStorage()` would work. While it wouldn't be a breaking change, it may make the subscription noisier for some users. But any noise could be filtered out, easily enough.

In my immediate use case, I have numerous forms for creating, updating, viewing, and deleting entities (CRUD). I'm sure I'll encounter more use cases as the app is developed. This is not a single page app, but I intend to make it a Progressive Web App. For example, here's an approximation of what I do on a submit handler.

```js
// `delay` is a Promise that resolves within a given number of milliseconds.
// `set` abstracts around `storage.set`.
import { delay, set } from './store.js'

async function submit (event) {
  event.preventDefault()
  set('org/name.txt', name)
  await delay(100)
  window.location = './'
}
```

With changes to `onWrite`, I could make it this:

```js
import { set } from './store.js'

async function submit (event) {
  event.preventDefault()
  await set('org/name.txt', name)
  window.location = './'
}
```

---

And for additional context, this is my current `set` function. There's other things in the module that I'm not showing, but you can understand the gist of it.

```js
export function set (path, content) {
  const keypair = getKeypair()
  return storage.set(keypair, {
    format: 'es.4',
    path: resolvePath(path),
    content
  })
}
```

With changes to `onWrite`, this is likely how my custom `set` function would change:

```js
export async function set (relativePath, content) {
  const keypair = getKeypair()
  const path = resolvePath(relativePath)
  return new Promise((resolve) => {
    const unsubscribe = storage.onWrite.subscribe((writeEvent) => {
      if (writeEvent.kind === 'DOCUMENT_PERSIST' && writeEvent.document.path === path) {
        unsubscribe()
        resolve(writeEvent)
      }
    })
    storage.set(keypair, {
      format: 'es.4',
      path,
      content
    })
  })
}
```

**Comment by basham** [comment]
I haven't tested it (because I'm using the IndexedDB driver), but I'm guessing this issue is no longer relevant, now that Earthstar v7 is out. Perhaps it can be closed?

**Comment by sgwilym** [comment]
@basham No debouncing is being done right now in either the LocalStorage or IndexedDB drivers. I'm not sure whether it will — I think the LocalStorageDriver might not need it as it's meant for small amounts of data, and eventually the IndexedDB driver will be more sophisticated and will not need anything like this.

I'm glad the IndexedDB driver is working out for you!
