### ISSUE TITLE
Bundling issues with Snowpack

### ISSUE THREAD

**Issue by basham** [earthstar-project/earthstar#233]
Earthstar suggests importing the browser bundle from a CDN.

```html
<script type="module">
  import * as Earthstar from "https://cdn.earthstar-project.org/js/earthstar.bundle.v7.1.0.js";
</script>
```

However, I would like to install the bundle locally, so my build environment ([Snowpack](https://www.snowpack.dev/)) can include it and my PWA library ([Workbox](https://developers.google.com/web/tools/workbox)) can cache it.

Could you please add the browser bundle to the npm package?

In the meantime, I am solving it by referencing a [custom repo](https://github.com/basham/earthstar-bundle) that includes the bundle, in `package.json`.

```json
{
  "dependencies": {
    "earthstar": "basham/earthstar-bundle#v7.1.0"
  }
}
```

**Comment by sgwilym** [comment]
I saw this too when trying to build something! Sorry for the inconvenience, this will be done very soon.

**Comment by sgwilym** [comment]
Hey. I've publish v8.0.0 to NPM. I need to add this to the docs, but you can import browser / node specific stuff this way:

```
import { Replica } from "earthstar";
import { ReplicaDriverIndexedDB } from "earthstar/browser";
```

**Comment by basham** [comment]
The import path changes are nice. I was doing this in one part of my code:

```js
import { ReplicaDriverSqlite } from 'earthstar/src/entries/node.js'
```

It'll be nice doing this:

```js
import { ReplicaDriverSqlite } from 'earthstar/node'
```

However, I'm not seeing the bundle in the npm package.

https://unpkg.com/browse/earthstar@8.0.0/

Without the pre-made bundle, I will need to use [node polyfills in Snowpack](https://www.snowpack.dev/reference/configuration#packageoptionspolyfillnode) to make it work. Because the "universal" Earthstar code still depends on things like "buffer" and other such things. (I'd have to work on finding the full list of import issues, if you'd find that valuable.)

**Comment by sgwilym** [comment]
This is valuable, as I have not been able to test all these environments! A big part of reworking earthstar was to put all the node specific stuff in its own compartment, so we definitely don't want Buffer sneaking in via the universal or browser imports. Do you get any stack traces for what's importing it?

**Comment by basham** [comment]
I know I encountered problems with `buffer` with either Earthstar v6 or v7. But I'm not seeing that particular issue now.

After some more investigation, the problem is more complex than I hoped. There are many direct and indirect references to [`earthstar/esm/deps.js`](https://unpkg.com/browse/earthstar@8.0.0/esm/deps.js) from modules that are referenced in both the `universal` and `browser` entries. As such, all of these dependencies are trying to be converted to work in the browser:

- chalk
- fast-deep-equal
- fast-json-stable-stringify
- rfc4648
- sha256-uint8array
- @noble/ed25519
- concurrency-friends
- earthstar-streaming-rpc
- earthstar-streaming-rpc/browser

Some of these do not compile cleanly in Snowpack (such as `chalk`).

Some of these compile but error in the browser. This browser error suggests some indirect dependency:

```
SyntaxError: The requested module '/_snowpack/pkg/@sgwilym.urlpattern-polyfill.v1.0.0-rc8.js' does not provide an export named 'URLPattern'
```

Unfortunately, this type of issue is one in which you don't know the full extent of the problem. You solve it in one area, just to then reveal the next. You don't know you're done until you are done. So, I can't report in much of any helpful detail right now what the particular issues are.

Offering the browser bundle in the npm package is the safest and quickest way to provide a working solution for browsers. But if really wanting to provide a ESM module setup compatible with browsers, then more work needs to be done to isolate the dependencies in [`deps.ts`](https://github.com/earthstar-project/earthstar/blob/v8.0.0/deps.ts) according to their compatible environments.

**Comment by basham** [comment]
More specifically, as a start, you may want to consider splitting up `deps.ts` into `browser-deps.ts`, `node-deps.ts`, and `universal-deps.ts`. But I'm sure it'll get more complex than that, as you dive deeper into it.

**Comment by basham** [comment]
[`crypto-driver-chloride.js`](https://unpkg.com/browse/earthstar@8.0.0/esm/src/crypto/crypto-driver-chloride.js) is a good example of how the dependencies are handled well. It depends on the `chloride` and `buffer` packages, but it is only referenced by the [`node.js` entry](https://unpkg.com/browse/earthstar@8.0.0/esm/src/entries/node.js). As a result, these two dependencies are never encountered by the browser and do not become a problem.

**Comment by sgwilym** [comment]
@basham I won't bore you with the details, but dependencies are already being mapped for different platforms. This is about mapping the right ones to the NPM package.

I have Earthstar bundling in a NPM CRA app as of yesterday. I will start building a Snowpack app and see what I can do.

**Comment by basham** [comment]
As some additional tests, instead of having Snowpack try to build Earthstar itself, I switched to using CDN module imports. But both tests results in browser errors.

## Skypack

- https://cdn.skypack.dev/earthstar
- https://cdn.skypack.dev/earthstar/browser

Error (same as I described with the local Snowpack build, yesterday):

```
SyntaxError: The requested module '/_snowpack/pkg/@sgwilym.urlpattern-polyfill.v1.0.0-rc8.js' does not provide an export named 'URLPattern'
```

## ESM.sh

- https://esm.sh/earthstar/
- https://esm.sh/earthstar/browser

```
SyntaxError: The requested module '/v66/concurrency-friends@5.2.0/es2021/concurrency-friends.js' does not provide an export named 'Lock'
```

---

So, yes, this rabbit hole (as you say) is what I was fearing. It is certainly not worth your limited time trying to resolve all these issues right now. Thanks for exploring it for a bit, though.

The Deno-compiled browser bundle does work. If that is included in the NPM package, that will provide more options to users of Earthstar, with little additional time on your end.

**Comment by sgwilym** [comment]
@basham esm.sh and skypack are definitely going to give you weird results. Importing this way means you're import a module built for ESM, translated to a NPM module, and then translated _back_ to NPM again.

If you're going to use a URL import, why not go back to where this all started?

```js
import * as Earthstar from "https://cdn.earthstar-project.org/js/earthstar.bundle.v7.1.0.js";
```

This would import the made-for-ESM bundle.

**Comment by basham** [comment]
I do not intend to use a URL import of Earthstar. I just did the Skypack and ESM.sh test as a way to see if those systems somehow could resolve this issue in a way that the other approaches seems to not be doing right now.

I want a local reference to the Earthstar browser bundle so that Snowpack will copy it to the build folder and then Workbox can cache it with a service worker up front. I want all dependencies hosted in the same place, so that there's only one potential place for network errors (where the app is hosted). Also, by installing Earthstar via npm, I can easily know when Earthstar has a new version when I check for new versions of all dependencies (via `npm outdated`) and manually update them. Taken together, this provides a better offline experience for users, while simplifying the build process and maintenance of the app.

If I would stop using the "basham/earthstar-bundle#v7.1.0" repo, then it complicates other parts of the build process. I would write a Node script to pull down the bundle from the CDN. Then that needs to be saved in a temporary folder. Then I need to make Snowpack aware of it. I'm essentially needing to recreate what npm does for me, for the sake of a single dependency.

Is there a concern with including the bundle in the npm package?
