### ISSUE TITLE
Replicas should wait for ReplicaDriverIndexedDB to be ready

### ISSUE THREAD

**Issue by basham** [earthstar-project/earthstar#235]
If you have a replica configured with ReplicaDriverIndexedDB, there isn't a guarantee that the database is ready when you initially call a method on it.

For example, even though I have set a particular doc and know it is there, this will return undefined soon after page load.

```js
const doc = await replica.getLatestDocAtPath('/doc.txt')
```

I've gotten around it first by putting in a delay. But then after digging around, I replaced the delay with an await on IndexedDB.

```js
await replica.replicaDriver.getIndexedDb()
const doc = await replica.getLatestDocAtPath('/doc.txt')
```

However, it would be better if any replica methods have this await built in. It may require some new method on the drivers, that resolves a promise when the driver is ready.

**Comment by sgwilym** [comment]
This has been fixed as of 8.1.2!
