### ISSUE TITLE
Unable to run Earthstar due to broken dependency

### ISSUE THREAD

**Issue by AnActualEmerald** [earthstar-project/earthstar#258]
## What's the problem you want solved?
The `crayon_chalk_aliases` dependency is broken because crayon v3 removed `types.ts` from their root directory
![image](https://user-images.githubusercontent.com/4367791/169218315-ced65611-60b4-4616-aa8d-cabeeb1e0a3f.png)

## Is there a solution you'd like to recommend?
Switch to a maintained crayon dependency, perhaps using https://deno.land/x/crayon@3.1.0/src/extensions/chalk_aliases.ts

I don't know how prevalent this library is but I'd be willing to lend a hand with swapping it out

**Comment by sgwilym** [comment]
Fix published in v9.3.3! Thanks for the report.
