### ISSUE TITLE
More consistent error reporting

### ISSUE THREAD

**Issue by cinnamon-bun** [earthstar-project/earthstar#27]
## What's the problem you want solved?
This code uses a variety of paradigms for reporting errors.  Variously:
* Return null on error, with no access to the reason for error
* Raise exception
* Return { result, err }

## Is there a solution you'd like to recommend?
Choose and standardize on one style.

Here are some options:
https://github.com/earthstar-project/earthstar/blob/master/ignore/errorstyles.ts

Criteria:
* Typescript understands it
* Usable from plain Javascript
* Easy to use (short code)
* Easy to understand (widely used)
* Returns rich error information
* Serializable (so errors can be returned from pub servers over HTTP)
* Works well with async functions

**Comment by cinnamon-bun** [comment]
Which of these would you most enjoy using?  I just rewrote a bunch of code in style D (classic try/catch) and it's feeling messy now because Typescript can't track which functions throw exceptions and which don't.

Thoughts?

Actual working code examples are in [errorstyles.ts](https://github.com/earthstar-project/earthstar/blob/master/ignore/errorstyles.ts).

**A. Custom error type:**
```ts
type Err = {err: string};
let makeDog = () : Dog | Err => ...
let dog = makeDog()
if ('err' in dog) { console.log('oops'); }
```

**B. Result<T> style using the built-in node Error type.**
(remember that `Result<T> = T | Error`)
```ts
let makeDog = () : Result<Dog> => ...
let dog = makeDog()
if (dog instanceof Error) { console.log('oops'); }
```

**C. Node style: [err, result]**
```ts
let makeDog = () : [string | null, Dog | null] => ...
let [err, dog] = makeDog()
if (err) { console.log('oops'); }
else { console.log(dog.name); } // dog could still be null here. :(
```

**D. Classic throw/catch**
```ts
let makeDog = () : Dog => ...
let dog = makeDog()
// oops, we forgot to catch that error because Typescript doesn't track it for us
// let's try again
try {
    let dog = makeDog()
} catch (err) {
    console.log('oops');
}
```

**Comment by sgwilym** [comment]
I like A! It allows you to build much richer error types, and TS can keep tabs on it. It's more work than B, but B shifts work onto clients which then have to parse strings from Errors into different kinds of errors.

As you mentioned, TS doesn't deal with throw/catch well, and is more unwieldy with async code.

**Comment by cinnamon-bun** [comment]
Done!  It was a [big commit](https://github.com/earthstar-project/earthstar/commit/8b6ce847a056619270adb3a910acda3de5c36177).

[Docs about the new error handling.](https://github.com/earthstar-project/earthstar/blob/master/CONTRIBUTING.md#errors-and-exceptions)

I chose style B but returning [custom subclasses of the built-in node Error class](https://github.com/earthstar-project/earthstar/blob/master/src/util/types.ts#L11-L39).  We can add custom fields, and easily check which kind of error it is using `err instanceof ValidationError`.

I thought it would be a bit more normal to use node Errors instead of making our own ad-hoc Error type.  It also means we can `throw` them if circumstances demand it, which happens in a few places (especially class constructors which can't return errors so we have to throw them).

This is a **breaking change**.  Things that used to return true/false on success/failure now return something different, so you can't just check for trueyness or falseyness:

```ts
// don't do this anymore
if (storage.set(...)) { // success! }

// do this
if (notErr(storage.set(...))) { // success! }
```

The new [`isErr` and `notErr` helper functions](https://github.com/earthstar-project/earthstar/blob/master/src/util/types.ts#L36-L37) check if something is an error.
