### ISSUE TITLE
Consider switching from base58 to base32 to improve URL compatability

### ISSUE THREAD

**Issue by cinnamon-bun** [earthstar-project/earthstar#29]
### Problem
Workspace names need to be case sensitive to preserve their base58 secrets.

URL locations are supposed to be NOT case sensitive, and some URL parsers will lowercase them for you.

This matters if we want to make our own URL scheme like `earthstar://` without fighting the URL parser.

### Solution?
Switch workspace and author addresses to lowercase base32 encoding.

Secrets will be 52 chars long instead of 44.  This isn't significantly worse.

See [this comment](https://github.com/cinnamon-bun/earthstar/issues/28#issuecomment-659710941) for details.

**Comment by cinnamon-bun** [comment]
Done!

**Comment by christianbundy** [comment]
Congrats on the change!
