### ISSUE TITLE
[FR] File size limit > 4 mb

### ISSUE THREAD

**Issue by catleeball** [earthstar-project/earthstar#293]
## Feature request: sync files larger than 4 megabytes

Currently the documentation lists that the max file size in Earthstar is 4mb, but that the limitation will be addressed in the near future.

![Screenshot from Earthstar documentation: "Right now the maximum size of an Earthstar document is 4 megabytes."](https://user-images.githubusercontent.com/43632885/210184104-b3237272-f35c-43dc-824f-177124c7699f.png)

## Question

Do you know if there's currently an issue / milestone / release log I can follow to be notified when this limit is increased? Earthstar seems really cool, and I'm eager to use it, but the limit is a blocker for most workflows I would like to use Earthstar for!

## Use cases

This is handy for sharing most media larger than text files, e.g.:

- Share a photo album
- Large-ish PDFs
- Videos
- Datasets

## Workarounds

Currently, this can we worked-around with multi-part archives. This is somewhat painful, particularly for files that may be modified semi-regularly (e.g. a big spreadsheet, powerpoint, doc, etc) since the workflow becomes:

- Decompress multi-part archive to view / modify
- Make modifications
- Update or replace old multi-part archive
- Sync

## Notes

Thank you for your hard work on this software! :)

**Comment by sgwilym** [comment]
Hi @catleeball! You're absolutely right, and you've arrived at just the right time. I've _just_ released v10.0.0 of Earthstar, which has APIs for syncing data of any size. It's been tested with gigabyte-sized videos down to teeny tiny text files.

Please check the new README to see how these APIs work. I'm looking forward to hearing if these suit your workflows?
