### ISSUE TITLE
What is this key for in `syncReplicaAndFsDir` ?

### ISSUE THREAD

**Issue by johanbove** [earthstar-project/earthstar#303]
In function `syncReplicaAndFsDir` on line https://github.com/earthstar-project/earthstar/blob/05f3958087eeb45cc503b094d9e0c385033db2f8/src/sync-fs/sync-fs.ts#L267, there is a hard-coded key: `b4oymiquy7qobjgx36tejs35zeqt24qpemsnzgtfeswmrw6csxbkq`.  What is this for?

**Comment by sgwilym** [comment]
That is the base 32ed SHA 256 hash for an empty string.
