### ISSUE TITLE
Add ephemeral documents (deleteAfter a certain timestamp)

### ISSUE THREAD

**Issue by cinnamon-bun** [earthstar-project/earthstar#31]
## What's the problem you want solved?
It would be nice to have ephemeral documents that get deleted after a given date.  This helps with privacy and reduces storage needs.

## Is there a solution you'd like to recommend?
- [x] Add a new **optional** field to documents: `deleteAfter: <timestamp>`.
- [x] The Validator should consider the document invalid after the expiration date.  This prevents it from being synced.
- [x] Reads and queries should filter out expired documents, as if they don't exist
- [x] Reads and queries can trigger local deletion of expired documents when they're encountered (optional)
  - [x] StorageMemory
  - [ ] StorageSqlite doesn't do this yet.  It does filter out expired docs, it just doesn't delete them from the database when it encounters them.
- [x] Update docs
- [x] Validator should enforce that ephemeral docs use special character `!` in their path, and regular docs don't.  Add tests too.
- [ ] Storage implementations should proactively check for and delete expired documents occasionally, maybe at startup and every hour thereafter?  And upon `close()`, kill that recurring task.

**Comment by cinnamon-bun** [comment]
I added this in 4 commits on July 24, 2020: [a](https://github.com/earthstar-project/earthstar/commit/107b32a83d142e8609cede05a1d42c5b0a0f5510), [b](https://github.com/earthstar-project/earthstar/commit/6a6f7821ed5abd2c4585f9fa205c8e26aa691998), [c](https://github.com/earthstar-project/earthstar/commit/0c8fa041e0653edc11dbf5c6e47d20d80ccc054a), [d](https://github.com/earthstar-project/earthstar/commit/7a0e3a50d73526f39bb12f52d5cf04b3c62d36d0).

Ran into a design problem!  Consider this scenario:

* Start with a regular document at `/wiki/Kittens`, which exists on 10 peers in the network.
* Overwrite it with an ephemeral document on the same path, which expires in 5 seconds
* The ephemeral document spreads halfway across the network, replacing the regular document as it goes
* Then it expires while spreading and peers completely delete the ephemeral document
* The original regular document can now re-spread and conquer the network again, filling in the holes

But if the ephemeral document succeeds in reaching all the peers before it expires, it will extinguish the regular document.  In the end there will be nothing at all.

I don't like this unpredictability.  Imagine if a device has been offline for 5 months and comes back with some old regular documents that re-spread across the network...

Solutions:

A. Don't allow ephemeral docs to collide with regular docs on the same path.  Use special characters in ephemeral doc paths to indicate that they are ephemeral.

B. Regular docs always win over ephemeral docs, if they are on the same path, regardless of timestamps.  So an ephemeral doc just can't overwrite a regular doc.

C. Ephemeral docs don't get truly deleted, they only have their content deleted when the deadline passes.  The remainder of the doc keeps existing as an empty tombstone and can keep spreading through the network after the deadline.

I don't like C because the metadata for ephemeral docs will linger and accumulate, and we'd rather just delete it for privacy reasons.

I'm leaning towards B.  Thoughts?

**Comment by RangerMauve** [comment]
I like A a lot since it makes things more explicit and reduces the amount of cases you need to consider in an implementation.

B sounds good too.

**Comment by sgwilym** [comment]
I kind of like A as well, it seems very cut and dry. Maybe this is what you were already thinking, but I feel like if earthstar went with that the special character for an ephemeral doc should be in its 'file name':

e.g. like this if the special character was `?`
```
/docs/myephemeraldoc.md?
```

but not like this:
```
?/docs/myephemeraldoc.md
```

The reason being that I think clients are probably going to figure out the kinds of content they want to display using path prefixes, e.g. let's display everything under `/wiki`. If the special character appears within any but the last part of the path, then you'd need to make a special case for supporting ephemeral docs in your client (like... requesting the non-ephemeral and ephemeral path prefixes for docs, combining them...), whereas if the character is at the end you get it when you ask for all docs under `/wiki`.

**Comment by cinnamon-bun** [comment]
For option A...

## Choosing a special character

Paths are allowed to contain... (see [characters.ts](https://github.com/earthstar-project/earthstar/blob/master/src/util/characters.ts#L37)):

`/'()-._~!*$&+,:=?@%`  + letters and numbers

Those are all the characters that are allowed in regular web URL paths without using percent-encoding.  (That's why `"` and space are missing.)

Some already have meanings:

`?` -- query parameters in regular web URLs.  Maybe I should disallow it in paths, actually.
`~` -- earthstar permissions
`/` -- separating path components
`.` -- file extensions
`-` and `_` -- commonly used in filenames
`+` and `@` -- earthstar workspace and user sigils
`%` -- needed for percent-encoding

Here's what's left.  Which one feels "ephemeral"?

`'`
`(` `)`
`!` -- this is my favorite
`*` -- save this for querying, like `/wiki/*/Dogs`, eventually
`$`
`&`
`,`
`:`
`=`

## Where does it go in the path?

I'd propose... anywhere?

I agree usually you'd put it at the end of the path to avoid interfering with pathPrefix queries, but there might be reasons to put it elsewhere (in the middle?), so let's allow flexibility.  That's also why `~` permissions are allowed anywhere in the path.

**Comment by cinnamon-bun** [comment]
I've just removed `?` from allowed path characters to avoid it being interpreted as URL query parameters.

It would also be nice if paths were legal as regular filesystem paths, but that varies a lot across operating systems... and some filesystems aren't even case-sensitive... we'd have to make Earthstar paths be only lower-case...

**Comment by RangerMauve** [comment]
I think it'd be cool to have the symbol at the beginning of the "file name" portion of the path. Like `/foo/bar/!baz.json`.

`!` is nice cause it stands out as "This means something important" which could be handy since the document isn't gonna last long. :P

I also feel drawn to `&`, but that is also part of a query string so I dunno if that'd be confusing.

**Comment by sgwilym** [comment]
In the release notes I saw it mentioned that there should be a proactive hourly check for documents which are to be deleted. I was wondering... what if deletion happened whenever a document was 'touched', e.g. queried from IStorage? During which a document's `deleteAfter` would be checked, and the content deleted if it was less than now.

**Comment by cinnamon-bun** [comment]
@sgwilym 
> what if deletion happened whenever a document was 'touched', e.g. queried from IStorage?

Yeah!  That's B in the list below:

What do to about expired documents
* A. Filter it out of the returned query results as if it's not there
* B. Delete it when we notice it (e.g. when a query matches it)
* C. Delete them all proactively, maybe every hour that Earthstar is running

Progress
* A. is required.  done in ✅ memory, ✅ sqlite
* B. is optional.  only in ✅ memory so far.
* C. is required.  not implemented yet.

A and B are not sufficient to meet the privacy goals -- we don't want expired documents to fall through the cracks and lie around for a long time.  We want to try harder to get rid of that data to reduce the privacy risk.

(Obviously we can't guarantee it's deletion.  Devices might be offline for a long time, or could be dishonest.  But we should try the best we can.)
