### ISSUE TITLE
Syncer gets stuck on GraphQL pubs

### ISSUE THREAD

**Issue by cinnamon-bun** [earthstar-project/earthstar#51]
## What's the problem you want solved?

If the Syncer tries to talk to a GraphQL pub, it gets a 400 error response and dies while trying to parse JSON.  Then it never finishes the sync lifecycle and goes back to an idle state.

## Is there a solution you'd like to recommend?

Probably need to catch an error during JSON decoding.

(Uncertain if we want to support GraphQL pubs here in the core package or not; but at least it should fail cleanly)

**Comment by sgwilym** [comment]
Closing this as I've archived the earthstar-graphql-pub repo as of a few days ago. It was a fun experiment, but keeping it around means adding more things to learn and attend to for both maintainers and client authors.
