### ISSUE TITLE
Get Started doc in more flavors

### ISSUE THREAD

**Issue by judytuna** [earthstar-project/earthstar#56]
## What's the problem you want solved?

JavaScript (not TypeScript) version of the Get Started doc! 

## Notes from our tripling session =)

mkdir earthstarter
npm init, then press enter enter enter for all the defaults
npm install --save earthstar
this will take a minute. it's compiling sqlite, probably. 

hmm, earthstar is trying to use the new style of imports and disliking it. go back to the old version. 

const earthstar = require('earthstar');
const blabla = earthstar.blabla; over and over again

hacky way of making a new author keypair and save it. 

moving on to the todo code. it's got a bunch of functions, but no glue that makes the app work. that's up to you! 
peterson's taking out all the types like a typemonster. chomp chomp

**Comment by cinnamon-bun** [comment]
The tutorial has been rewritten to use plain Javascript and I've fixed the bugs in it.

https://github.com/earthstar-project/earthstar/blob/master/docs/tutorial.md
https://github.com/earthstar-project/earthstar/blob/master/docs/tutorial.js
