### ISSUE TITLE
Ignore an undefined value when validating query.history

### ISSUE THREAD

**Issue by sgwilym** [earthstar-project/earthstar#68]
When validating the `history` property on `Query`, an error will be thrown if the value is undefined. As this is one of those optional properties, that can happen pretty easily. If it's undefined maybe we can just ignore it?

https://github.com/earthstar-project/earthstar/blob/0641ebba6853ca93cb0c911cf8019dbc8eee56b8/src/storage/storageMemory.ts#L99

**Comment by cinnamon-bun** [comment]
Good catch!

Queries have been already run through `cleanUpQuery` which should ensure nothing is set to `undefined` by the time we get to the code you linked:
https://github.com/earthstar-project/earthstar/blob/0641ebba6853ca93cb0c911cf8019dbc8eee56b8/src/storage/storageMemory.ts#L45

But that's not quite doing the right thing:
https://github.com/earthstar-project/earthstar/blob/0641ebba6853ca93cb0c911cf8019dbc8eee56b8/src/storage/query.ts#L140-L160

I'll fix it and add tests.

**Comment by cinnamon-bun** [comment]
This will be resolved by PR #70
