### ISSUE TITLE
Lots of messages in the console about syncing

### ISSUE THREAD

**Issue by sgwilym** [earthstar-project/earthstar#69]
## What's the problem you want solved?

Earthstar logs a lot of messages to do with syncing while being used (and even when syncing is not enabled). These also pop up in places like test environments, where it becomes a bit of a drag searching for your test errors among hundreds of these messages.

They also appear in any web app that uses earthstar, which creates a similar problem with noise.

<img width="672" alt="CleanShot 2021-02-16 at 14 52 34@2x" src="https://user-images.githubusercontent.com/579491/108071998-a7da2a80-7066-11eb-9bf1-5c228fbdf584.png">

## Is there a solution you'd like to recommend?

Could this logging only be done if a certain argument is passed somewhere?

**Comment by cinnamon-bun** [comment]
How about a global singleton that sets log detail levels?

```ts
import {
    setLogLevels
} from 'earthstar'

setLogLevels({
    // many various kinds of logs, each default to zero but can be increased for more detail
    sync: 2,
    storage: 1,
});
```

**Comment by sgwilym** [comment]
@cinnamon-bun Something like that sounds great. Maybe I'll take a crack at this myself!

**Comment by cinnamon-bun** [comment]
@sgwilym 

The various kinds of log messages are defined in `src/util/log.ts`.
