### ISSUE TITLE
docs – blobs

### ISSUE THREAD

**Issue by nichoth** [earthstar-project/earthstar#87]
## What's the problem you want solved?

document blobs

## Is there a solution you'd like to recommend?

Was wondering if this is the up to date place for info about blobs — https://github.com/earthstar-project/earthstar/issues/61

So from that issue, the current story is blobs should be base64 encoded in messages? or linked to in a message, hosted elsewhere?

My goal is to make an app that is like for photos, like instagram. am currently looking for ways to do it decentralizedly.

thank you

**Comment by cinnamon-bun** [comment]
Hi @nichoth !

Right now, the story is: you have to base64 encode your blobs in messages (e.g. Earthstar documents).

Problems right now:
* In browsers, we use localStorage which is limited to 5mb total per origin (not per message).  This does not affect node, only browsers.
* base64 encoding takes 33% more space

Things that will eventually help:
* #1 (IndexedDb support) will lift the storage limitation in browsers
* #61 (Better binary data support) will let us avoid base64 encoding to save more space

Also relevant:
* #89 Specify max size of an Earthstar document (there's no limit right now), it will probably be 3 to 5 mb, large enough for images

In the meantime, some workarounds:
* Our SQLite storage backend has no size limits.  If you run your app in node on localhost and serve regular webpages from there to browsers, that would work.  Or use Electron.
* Use small images and not very many
* Delete old images so they don't accumulate, either by regular deletion (overwrite them with empty documents) or using ephemeral documents that expire
* Or store your big blobs elsewhere, like IPFS

**Comment by sgwilym** [comment]
Folding this into #61
